// settingsVm.js — builds the SettingsView view-model from App state + actions.
// Pure function: no hooks, no side-effects. App calls this on every render.
export function buildSettingsViewModel({
  closeSettings,
  connState, latency, testConnection,
  settings, status,
  signOut,
  patchSettings,
  setDefScope,
  toggleSubdomains,
  newRule, setNewRule, addRule, removeRule,
  clearCaptures,
  version,
}) {
  return {
    closeSettings,
    connState,
    latency,
    wsUrl: settings.workspaceUrl || '',
    setWsUrl: (v) => patchSettings({ workspaceUrl: v }),
    testConnection,
    authUser: settings.authUser || '',
    authTenantName: settings.authTenantName || '',
    signOut,
    paired: status?.uploader?.paired,
    defScope: (settings.domainScopes || []).join(', '),
    setDefScope,
    includeSubdomains: settings.includeSubdomains !== false,
    toggleSubdomains,
    outOfScopeMode: settings.outOfScopeMode || 'tag',
    setOutOfScopeMode: (m) => patchSettings({ outOfScopeMode: m }),
    maxAssetMb: settings.maxAssetMb || 10,
    setMaxAssetMb: (n) => patchSettings({ maxAssetMb: n }),
    captureResponseBodies: settings.captureResponseBodies === true,
    toggleResponseBodies: () => patchSettings({ captureResponseBodies: !(settings.captureResponseBodies === true) }),
    denyDefaultProfile: settings.denyDefaultProfile !== false,
    toggleDefaultProfile: () => patchSettings({ denyDefaultProfile: !(settings.denyDefaultProfile !== false) }),
    denyRules: settings.denyRules || [],
    removeRule,
    newRule,
    setNewRule,
    addRule,
    clearCaptures,
    capturedCount: status.fileCount || 0,
    version,
  };
}
