// vendor-fonts.mjs — one-shot: download the latin woff2 subset for the popup fonts
// from Google Fonts and emit dist/fonts/*.woff2 + dist/fonts.css (@font-face).
// Run once: `node scripts/vendor-fonts.mjs`. Output is committed; not run at build.
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = resolve(root, 'dist/fonts');
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const families = [
  { name: 'Space Grotesk', css: 'Space+Grotesk:wght@400;500;600;700', slug: 'space-grotesk' },
  { name: 'IBM Plex Sans', css: 'IBM+Plex+Sans:wght@400;500;600;700', slug: 'ibm-plex-sans' },
  { name: 'JetBrains Mono', css: 'JetBrains+Mono:wght@400;500;700', slug: 'jetbrains-mono' }
];

async function main() {
  await mkdir(outDir, { recursive: true });
  let faceCss = '/* Auto-generated by scripts/vendor-fonts.mjs — latin subset, self-hosted. */\n';

  for (const fam of families) {
    const url = `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`;
    const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

    // iterate `/* subset */ @font-face { ... }` blocks; keep only the latin subset.
    // Google serves these as VARIABLE fonts: every requested weight points at the
    // same woff2. Group by URL and emit one @font-face per unique file with a
    // weight RANGE, so we store one file (not N identical copies) per family.
    const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
    const byUrl = new Map(); // url -> { weights:Set }
    let m;
    while ((m = re.exec(css)) !== null) {
      if (m[1] !== 'latin') continue;
      const block = m[2];
      const weight = Number((block.match(/font-weight:\s*(\d+)/) || [])[1] || 400);
      const woff2Url = (block.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
      if (!woff2Url) continue;
      if (!byUrl.has(woff2Url)) byUrl.set(woff2Url, new Set());
      byUrl.get(woff2Url).add(weight);
    }

    let idx = 0;
    for (const [woff2Url, weights] of byUrl) {
      const ws = [...weights].sort((a, b) => a - b);
      const range = ws.length > 1 ? `${ws[0]} ${ws[ws.length - 1]}` : `${ws[0]}`;
      const fileName = byUrl.size > 1 ? `${fam.slug}-${ws[0]}.woff2` : `${fam.slug}.woff2`;
      const bin = Buffer.from(await (await fetch(woff2Url, { headers: { 'User-Agent': UA } })).arrayBuffer());
      await writeFile(resolve(outDir, fileName), bin);
      faceCss += `@font-face{font-family:'${fam.name}';font-style:normal;font-weight:${range};font-display:swap;src:url('fonts/${fileName}') format('woff2');}\n`;
      console.log('saved', fileName, `weights ${range}`, bin.length, 'bytes');
      idx++;
    }
  }

  await writeFile(resolve(root, 'dist/fonts.css'), faceCss);
  console.log('wrote dist/fonts.css');
}

main().catch((e) => { console.error(e); process.exit(1); });
